Модуляция
htmlacademy-javascript/1483003-kekstagram-25 pull request #4
Opened 2022-03-11 14:29 UTC by Sanya481

Разбил код на модули. 
Оставил main.js , как точку входа.
Создал:
- data.js - для генерации данных
- util.js - для вспомогательных функций

---
:mortar_board: [Модуляция](https://up.htmlacademy.ru/javascript/25/user/1483003/tasks/9)

:boom: https://htmlacademy-javascript.github.io/1483003-kekstagram-25/4/

2022-03-11 16:35 UTC, Ldes requested changes
### Правки

- [x] Перенос функций из констант
Сейчас у тебя в файле неизменяемыми данными есть функции
Функции стоит расположить по их пренадлежности

- [ ] Вспомогательные функции
В норме, такие функции принимают на вход что-то не конкретное, а абстрактное, помогать реализовывать основную логику.
Иногда утилиты могут использовать внутри себя другие утилиты, становясь зависимыми. 
Если выбан путь функционального выражения при объявления функции - важен порядок, в котором они описаны в файле и зависимые должны быть ниже независимых)

- [ ] Функции основной логики, что работают с конкретными данными, константами, и принимаемыми от пользователя или от сервера например.
Основная логика запускается в файле точки входа, и для нас это main.js сейчас.

- [ ] Функции в модуль
Есть функции основной логики, которые могут быть объеденены по признаку ответственности, и выделены в модуль.
Например можно сделать модуль ответственный за тестовые данные, или модуль ответственный за комментарии а другой за посты)

- [ ] Перенос констант
В идеале `START_NUMBER` и `MAX_STEP` относятся к `getNextCommentId`, и не должны быть в утилитах
`getNextCommentId` в свою очередь относится к основной логике, которую можно вынести и в отдельный модуль

В таком случае с модулями, можно даже перекинуть константы имеющие отношение только модулю прям в него)

### Дополнительно
- [ ] Имена констант
Например имена `START_NUMBER` и `MAX_STEP` не достаточно явно дают понять, к чему конкретно относятся эти значения

- [ ] [Д5.](https://up.htmlacademy.ru/javascript/25/criteries#d5) Все функции объявлены единообразно.

Сейчас есть функции, что объявлены декларативно (isPositiveMaxNumbers), а есть через функциональное выражение (checkStringMaxLength)
Было бы здорово уже сейчас начинать переходить на единый стиль)

[Глава 2.7. Функции](https://up.htmlacademy.ru/javascript/25/book/2.7)

2022-03-11 16:35 UTC, Ldes commented on js/util.js
> +const MAX_STEP = 2;
Давай зададим этим контантам более точные имена, исходя из того, для чего они используются
И было бы здорово отнести их в файл, к остальным константам)

2022-03-11 16:35 UTC, Ldes commented on js/data.js
> +const makeUserPosts = () => Array.from({ length: POSTS_PHOTO_COUNT }, makePost);
В константах должны быть только неизменные данные ;)

2022-03-11 16:35 UTC, Ldes commented on js/util.js
> +const getNextCommentId = () => getNextRandomInt(START_NUMBER, MAX_STEP);
Относится к основной логике больше, так как отвечает за что-то конкретное, комментарии в нашем случае)

2022-03-11 16:35 UTC, Ldes commented on js/data.js
> +import {getRandomIntInclusive, getRandomArrayElement, getNextCommentId} from './util.js';
В файл с константами обычно ничего не прилетает снаружи, скорее наоборот он является источником данных для основной логики

2022-03-12 14:08 UTC, Sanya481 commented on js/data.js
> +const makeUserPosts = () => Array.from({ length: POSTS_PHOTO_COUNT }, makePost);
Не очень понял. Я пока смотрю как пользователь и для меня, что лайки, айдишники, фотографии опубликованные пользователем - будут изменяться же.! Так какие они неизменные получаются!?

2022-03-12 14:12 UTC, Sanya481 commented on js/util.js
> +const MAX_STEP = 2;
В функции , где используются эти константы. мы получаем целое неповторяющееся число.  Параметрами мы передаем туда число с которого будет начинаться отсчет и число, которым будет заканчиваться. Своего рода диапазон

2022-03-12 14:15 UTC, Sanya481 commented on js/util.js
> +
Функцию  isPositiveMaxNumbers только не получается перевести в стрелочную - ругается , что arguments обьявлены, но не используются

2022-03-12 18:31 UTC, Ldes reviewed
Константы и основные функции по пути решили зайти в бар)
Надо бы их вернуть, они ещё пригодятся

2022-03-12 18:31 UTC, Ldes commented on js/util.js
> +
Со стрелками да, у них среди прочего [нет своих аргументов](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Functions/Arrow_functions#%D1%81%D0%B2%D0%BE%D0%B4%D0%BA%D0%B0))

Но, если захотеть..) Нам может быть полезен [Spread syntax](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Spread_syntax)
Как вариант, можно указать явно параметр `...arguments` ([rest parameters](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Functions/Rest_parameters))
`...` в начале приводят к тому, что все переданные параметры будут записаны в массив, под именем arguments
```js
const isPositiveMaxNumbers = (...arguments) => {
  console.log(arguments);
  console.log(...arguments);
}
```
Давай глянем в консоли результаты
```js
isPositiveMaxNumbers();
isPositiveMaxNumbers(1, 2);
```
Так не обязательно делать, но есть и такой вариант ;)

2022-03-12 18:35 UTC, Ldes commented on js/data.js
> +const makeUserPosts = () => Array.from({ length: POSTS_PHOTO_COUNT }, makePost);
Да, они будут в последствии приходить от сервера
На текущем этапе мы с сервером не работаем, и для нас эти данные пока неизменны)

2022-03-12 19:53 UTC, Ldes commented on js/util.js
> +const MAX_STEP = 2;
Всё верно, и сейчас это понятно, пока кода мало)

Сейчас данные константы заведены для данной `getNextCommentId`
Представим, что у нас есть несколько разных уникальных идентификаторов получаемых подобным образом, но нужно стартовать и шагать их с разными значениями например

Есть очень классная схема, которую в своё время выкатили ребята из IBM
PRIME-MODIFIER-CLASS

Например, в нашем случае мы завели постоянные значения для параметров создания идентифиикатора комментария

- Мы сообщаем, к чему относится указанная переменная. Это необходимая часть.
У нас комментарии, а именно их идентификаторы
`COMMENT_ID` ...

- В конце, опционально, закрываем уточнением
`COMMENT_ID`, `COMMENT_ID`

- Далее, опционально, можем дать уточнить модификатор.
Например у нас есть максимальное значение шага, с которым увеличивается значения идентификатора комментария
`COMMENT_MAX_ID`, `COMMENT_START_ID`

2022-03-12 21:03 UTC, Ldes reviewed
Ещё пару моментов и двинем дальше 🚀
Красава 😻

2022-03-12 21:03 UTC, Ldes commented on js/generating-comments.js
> +const MAX_POSITIVE_INTEGER = 2;
Данные константы у нас относятся к генерации идентификатора комментария
Давай обозначим этот момент в именах соответствующих констант)

2022-03-13 14:37 UTC, Ldes commented on js/util.js
> +
Красавчик)
В целом, не обязательно, всё в стрелки приводить. Можно и не стрелочные функции использовать ;)
Главное знать, в чям между ними разница и остановиться либо на функциональном выражении или на декларативном объявлении.
Если потребуется, дай знать - разберём детальнее)

2022-03-13 14:37 UTC, Ldes commented on js/util.js
> +  }
Вообще есть критерий [Д13.](https://up.htmlacademy.ru/javascript/25/criteries#d13) В проекте не должно быть избыточных проверок.
Данные поверки опциональны, в рамках задания и критиериев можно было бы подумать что и лишними могут быть может. Мы делаем поведение функции более однозначным и предсказуемым.

2022-03-13 14:37 UTC, Ldes commented on js/generating-posts.js
> +const MAX_LIKES = 200;
Для единообразия, было бы круто работать по одной схеме именования 
PRIME-MODIFIER-CLASS

PRIME - COMMENT_ID
MODIFIER - MAX
CLASS - ID

2022-03-13 14:37 UTC, Ldes commented on js/util.js
> +// https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/random
Комментарий загулял
Давай уберём его, или привдём туда, где акутален будет)

2022-03-13 23:38 UTC, merged